[build]
edge_functions = "edge_functions"

[[edge_functions]]
path = "/github_access_token"
function = "github_access_token"

[[edge_functions]]
cache = "manual"
pattern = "/rsshub(.*)"
function = "rsshub"

[[edge_functions]]
path = "/ai_proxy/*"
function = "ai_proxy"
