[build]
edge_functions = "edge_functions"

[[edge_functions]]
path = "/github_access_token"
function = "github_access_token"

[[edge_functions]]
cache = "manual"
pattern = "/rsshub(.*)"
function = "rsshub"

[[edge_functions]]
path = "/gemini_proxy/*"
function = "gemini_proxy"

[[edge_functions]]
path = "/openai/*"
function = "openai"

[[edge_functions]]
path = "/grok/*"
function = "grok"

[[edge_functions]]
path = "/claude_proxy/*"
function = "claude_proxy"
